---

- name: "install goenv"
  ansible.builtin.command: anyenv install goenv
  args:
    creates: "{{ ansible_user_dir }}/.anyenv/envs/goenv/bin/goenv"

- name: "get installed versions"
  ansible.builtin.command: |
    fish -lc 'goenv versions'
  changed_when: false
  register: installed_versions

- name: "install golang"
  ansible.builtin.command: |
    fish -lc 'goenv install {{ item | quote }}'
  when: |
    golang.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ golang.versions }}'

- name: "get global version"
  ansible.builtin.command: |
    fish -lc 'goenv global'
  register: global_golang
  changed_when: false

- name: "set global golang"
  ansible.builtin.command: |
    fish -lc 'goenv global {{ golang.versions[0] | quote }}'
  when: global_golang.stdout != golang.versions[0]

- name: "install packages"
  environment:
    GOPATH: '{{ golang.path }}'
  ansible.builtin.command: |
    fish -lc 'go get -u {{ item | quote }}'
  with_items: '{{ golang.packages }}'
  when: golang.packages
  changed_when: false
