---

- name: "install goenv"
  ansible.builtin.command: anyenv install goenv
  args:
    creates: "{{ ansible_user_dir }}/.anyenv/envs/goenv/bin/goenv"

- name: "get installed versions"
  ansible.builtin.command: |
    fish -lc 'goenv versions'
  changed_when: false
  ignore_errors: true
  register: installed_versions

- name: "install golang"
  ansible.builtin.command: |
    fish -lc 'goenv install {{ item | quote }}'
  when:
    - golang.versions is defined
    - 'item|string not in installed_versions.stdout'
  with_items: '{{ golang.versions }}'

- name: "get global version"
  ansible.builtin.command: |
    fish -lc 'goenv global'
  register: global_golang
  changed_when: false

- name: "set global golang"
  ansible.builtin.command: |
    fish -lc 'goenv global {{ golang.versions[0] | quote }}'
  when: global_golang.stdout != golang.versions[0]

- name: "set global golang"
  ansible.builtin.command: |
    fish -lc 'env | grep -i go'

- name: "set global golang"
  ansible.builtin.command: |
    fish -lc 'which go'

- name: "set global golang"
  ansible.builtin.command: |
    fish -lc 'echo $PATH'

- name: "install packages"
  ansible.builtin.command: |
    fish -lc 'go install {{ item | quote }}'
  with_items: '{{ golang.packages }}'
  when: golang.packages
  register: go_install_result
  environment:
    PATH: >-
      {{- anyenv.envs_dir -}}/goenv/shims:
      {{- lookup("env", "PATH") -}}
  changed_when:
    - '"Downloading" in go_install_result.stderr'
