---

- name: "install chezmoi"
  community.general.homebrew:
    name:
      - chezmoi
  tags: homebrew

- name: "chezmoi init"
  ansible.builtin.command: chezmoi init --apply .
  args:
    chdir: "{{ ansible_user_dir }}/dotfiles"
    creates: "{{ ansible_user_dir }}/.local/share/chezmoi"

- name: "chezmoi update"
  ansible.builtin.command: chezmoi update --force
  register: chezmoi_update
  changed_when: '"Updating" in chezmoi_update.stderr'
