---

- name: "install chezmoi"
  community.general.homebrew:
    name:
      - chezmoi
  tags: homebrew

- name: "chezmoi init"
  ansible.builtin.command:
    cmd: chezmoi init {{ dotfiles.repo }} --branch {{ dotfiles.branch }}
  args:
    creates: "{{ ansible_user_dir }}/.local/share/chezmoi"

- name: "chezmoi apply current checkout"
  ansible.builtin.command:
    argv:
      - chezmoi
      - --source
      - "{{ dotfiles.checkout }}/config"
      - --working-tree
      - "{{ dotfiles.checkout }}"
      - apply
      - --force
      - --verbose
  register: chezmoi_apply
  changed_when: chezmoi_apply.stdout | length > 0
