packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim
  - less

brew:
  taps:
    - carlocab/personal
  casks:
    - 1password
    - alacritty
    - alt-tab
    - aws-vault
    - chatgpt
    - google-chrome
    - hiddenbar
    - kdiff3
    - microsoft-outlook
    - rectangle
    - slack
    - spotify
    - telegram
  packages:
    common:
      - bat
      - coreutils
      - direnv
      - duf
      - dust
      - eza
      - fd
      - fzf
      - gh
      - ghq
      - git-delta
      - highlight
      - jq
      - lazygit
      - mise
      - yq
      - ripgrep
      - sponge
      - tree
      - zoxide
    darwin:
      - carlocab/personal/unrar
      - dockutil
      - switchaudio-osx
      - ffmpeg
      - gawk
      - gnu-sed
      - wget
      - xz
    linux: []

dotfiles:
  repo: "https://github.com/shmileee/dotfiles"
  branch: "master"
  checkout: "{{ playbook_dir }}/../../.."

dockitems:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
  - name: Alacritty
    path: "/Applications/Alacritty.app"
  - name: Slack
    path: "/Applications/Slack.app"
  - name: ChatGPT
    path: "/Applications/ChatGPT.app"
  - name: Telegram
    path: "/Applications/Telegram.app"
  - name: Spotify
    path: "/Applications/Spotify.app"
  - name: Microsoft Outlook
    path: "/Applications/Microsoft Outlook.app"
  - name: Calendar
    path: "/System/Applications/Calendar.app"
  - name: System Settings
    path: "/System/Applications/System Settings.app"
  - name: Downloads
    path: "{{ ansible_facts['user_dir'] }}/Downloads"
    section: others
    options: [--view, auto, --display, stack, --sort, dateadded]

keyboard_key_codes:
  caps_lock: 30064771129
  escape: 30064771113

darwin_hotkeys:
  # remap "show spotlight search` to `⌘ + g`
  64:
    parameters: [103, 5, 1048576]
    enabled: true
  # disable "select the previous source in input menu"
  60:
    parameters: [32, 49, 262144]
    enabled: false
  # remap "select the next source in input menu" to `⌘ + space`
  61:
    parameters: [32, 49, 1048576]
    enabled: true
