packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim
  - less

brew:
  taps:
    - carlocab/personal
  casks:
    - 1password
    - alacritty
    - alt-tab
    - aws-vault
    - hiddenbar
    - kdiff3
    - rectangle
    - slack
    - spotify
    - telegram
  packages:
    common:
      - bat
      - coreutils
      - direnv
      - duf
      - dust
      - eza
      - fd
      - fzf
      - gh
      - ghq
      - git-delta
      - highlight
      - jq
      - lazygit
      - mise
      - yq
      - ripgrep
      - sponge
      - tree
      - zoxide
    darwin:
      - carlocab/personal/unrar
      - dockutil
      - switchaudio-osx
      - ffmpeg
      - gawk
      - gnu-sed
      - wget
      - xz
    linux: []

dotfiles:
  checkout: "{{ playbook_dir }}/../../.."

dockitems:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
  - name: Alacritty
    path: "/Applications/Alacritty.app"
  - name: Slack
    path: "/Applications/Slack.app"
  - name: ChatGPT
    path: "/Applications/ChatGPT.app"
  - name: Telegram
    path: "/Applications/Telegram.app"
  - name: Spotify
    path: "/Applications/Spotify.app"
  - name: Microsoft Outlook
    path: "/Applications/Microsoft Outlook.app"
  - name: Calendar
    path: "/System/Applications/Calendar.app"
  - name: System Settings
    path: "/System/Applications/System Settings.app"
  - name: Downloads
    path: "{{ ansible_facts['user_dir'] }}/Downloads"
    section: others
    view: auto
    display: stack
    sort: dateadded

keyboard_key_codes:
  caps_lock: 30064771129
  escape: 30064771113

darwin_hotkeys:
  # remap "show spotlight search` to `⌘ + g`
  "64":
    enabled: true
    value:
      parameters: [103, 5, 1048576]
      type: standard
  # disable "select the previous source in input menu"
  "60":
    enabled: false
    value:
      parameters: [32, 49, 262144]
      type: standard
  # remap "select the next source in input menu" to `⌘ + space`
  "61":
    enabled: true
    value:
      parameters: [32, 49, 1048576]
      type: standard

tmux_plugins:
  - repo: https://github.com/tmux-plugins/tpm
    name: tpm
    version: 7bdb7ca33c9cc6440a600202b50142f401b6fe21
    update: true
  - repo: https://github.com/shmileee/opencode-contextual-notifier
    name: opencode-contextual-notifier
    version: eebf6c146a14d860ece6242564ba8cddb4819a10
    update: true
  - repo: https://github.com/tmux-plugins/tmux-yank
    name: tmux-yank
    version: acfd36e4fcba99f8310a7dfb432111c242fe7392
    update: true
  - repo: https://github.com/tmux-revamped/tmux-kube-revamped
    name: tmux-kube-revamped
    version: 810bfb0b1f55bc2cef08a3ca745fa466d0e7c4c3
    update: true
