---
- hosts: 127.0.0.1
  strategy: linear
  connection: local

  vars_files:
    - config.yaml

  roles:
    - name: common
      tags: common

    - name: fonts
      tags: fonts

    - name: dotfiles
      tags: dotfiles

    - name: fish
      tags: fish

    - name: mise
      tags: mise

    - name: neovim
      tags: neovim

    - name: docker
      tags: docker
      when: not (lookup('env', 'DOCKERIZED') | bool)

    - name: tmux
      tags: tmux

    - name: system_defaults
      tags: system_defaults
