---
- name: "configure workstation"
  hosts: 127.0.0.1
  strategy: linear
  connection: local

  vars_files:
    - config.yaml
    - vars/runtime.yaml

  environment:
    PATH: "{{ workstation_path }}"
  roles:
    - role: bootstrap_prerequisites
      tags: bootstrap_prerequisites

    - role: homebrew
      tags:
        - homebrew
        - homebrew_install

    - role: common
      tags: common

    - role: fonts
      tags: fonts

    - role: dotfiles
      tags: dotfiles

    - role: fish
      tags: fish

    - role: mise
      tags: mise

    - role: neovim
      tags: neovim

    - role: docker
      tags: docker
      when: not dockerized

    - role: tmux
      tags: tmux

    - role: system_defaults
      tags: system_defaults

    - role: handoff
      tags: handoff
