---
- hosts: localhost
  strategy: linear
  roles:
  - name: common
    tags: common

  - name: fonts
    tags: fonts

  - name: dotfiles
    tags: dotfiles

  - name: fish
    tags: fish

  - name: neovim
    tags: neovim

  - name: lunarvim
    tags: lunarvim

  - name: anyenv
    tags: anyenv

  - name: docker
    tags: docker

  - name: go
    tags: go

  - name: tmux
    tags: tmux

  - name: python
    tags: python

  - name: kubernetes
    tags: kubernetes
