repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 44.50.3
    hooks:
      - id: renovate-config-validator
        args: [--strict]

  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks dir --redact --no-banner .
        language: system
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix --select=E4,E7,E9,F,B --ignore=E402,B905
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
      - id: stylua
        name: stylua
        entry: stylua
        language: system
        types: [lua]
      - id: chezmoi-templates
        name: chezmoi templates
        entry: chezmoi execute-template --file
        language: system
        files: \.tmpl$
      - id: shfmt
        name: shfmt
        entry: shfmt --write --indent 2 --binary-next-line --case-indent --space-redirects
        language: system
        types: [shell]
      - id: fish-indent
        name: fish_indent
        entry: fish_indent --write
        language: system
        files: \.fish$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        types: [yaml]
      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        files: ^\.github/workflows/.*\.ya?ml$
        types: [yaml]
      - id: zizmor
        name: zizmor
        entry: zizmor --min-severity medium --min-confidence medium
        language: system
        files: ^\.github/(actions|workflows)/.*\.ya?ml$
        types: [yaml]
      - id: ansible-lint
        name: ansible-lint
        entry: env ANSIBLE_CONFIG=scripts/common/ansible/ansible.cfg ansible-lint scripts/common/ansible
        language: system
        pass_filenames: false
        files: ^scripts/common/ansible/
