repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt --write --indent 2 --binary-next-line --case-indent --space-redirects
        language: system
        types: [shell]
      - id: fish-indent
        name: fish_indent
        entry: fish_indent --write
        language: system
        files: \.fish$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        types: [yaml]
      - id: ansible-lint
        name: ansible-lint
        entry: env ANSIBLE_CONFIG=scripts/common/ansible/ansible.cfg ansible-lint scripts/common/ansible
        language: system
        pass_filenames: false
        files: ^scripts/common/ansible/
