---
extends: relaxed

rules:
  comments:
    min-spaces-from-content: 1
  line-length: disable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  truthy:
    allowed-values: ["true", "false", "on"]
