[settings]
experimental = true
legacy_version_file = false

[tools]
"aqua:twpayne/chezmoi" = "2.72.0"
"pipx:ansible-core" = "2.21.3"
"pipx:ansible-lint" = "26.8.0"
"pipx:yamllint" = "1.38.0"
prek = "0.4.14"
shellcheck = "0.11.0"
shfmt = "3.13.1"
