---

- name: "install packages"
  community.general.npm:
    name: '{{ item }}'
    global: true
    executable: '{{ anyenv.envs_dir }}/nodenv/shims/npm'
  with_items: '{{ nodejs.packages }}'
  when: nodejs.packages
