---

- name: "install tmux"
  community.general.homebrew:
    name: tmux
    state: latest
  tags: homebrew

- name: "install tmux plugins"
  ansible.builtin.git:
    repo: "{{ item['repo'] }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/plugins/{{ item['name'] }}"
    version: "{{ item['version'] }}"
    update: "{{ item['update'] }}"
  loop: "{{ tmux_plugins }}"
  loop_control:
    label: "{{ item['name'] }}"
