---

- name: Install macOS fonts
  ansible.builtin.import_tasks: darwin.yaml
  when: ansible_facts["os_family"] == "Darwin"

- name: Install Debian fonts
  ansible.builtin.import_tasks: debian.yaml
  when: ansible_facts["os_family"] == "Debian"
