---

neovim_destination_directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"

neovim_build_dependencies:
  - autoconf
  - automake
  - cmake
  - curl
  - doxygen
  - g++
  - gettext
  - libtool
  - libtool-bin
  - ninja-build
  - pkg-config
  - unzip
