---

  # TODO: make build from source platforms independent
- import_tasks: build.yaml
  when:
    - neovim.build_from_source
    - not (lookup('env', 'DOCKERIZED') | bool)

- block:
    - name: "require arm64 architecture"
      ansible.builtin.assert:
        that:
          - ansible_architecture == "aarch64"
        fail_msg: "The Docker E2E Neovim binary is arm64-only"

    - name: "download arm64 release archive"
      ansible.builtin.get_url:
        url: >-
          https://github.com/neovim/neovim/releases/download/v{{
          neovim.binary_version }}/nvim-linux-arm64.tar.gz
        dest: /tmp/nvim-linux-arm64.tar.gz
        mode: '0644'
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: "remove previous release"
      become: true
      ansible.builtin.file:
        path: /opt/nvim-linux-arm64
        state: absent

    - name: "install release archive"
      become: true
      ansible.builtin.unarchive:
        src: /tmp/nvim-linux-arm64.tar.gz
        dest: /opt
        remote_src: true

    - name: "link executable"
      become: true
      ansible.builtin.file:
        src: /opt/nvim-linux-arm64/bin/nvim
        dest: /usr/local/bin/nvim
        state: link
        force: true

    - name: "remove leftovers"
      ansible.builtin.file:
        path: "/tmp/nvim-linux-arm64.tar.gz"
        state: absent

  when: >-
    not neovim.build_from_source or
    (lookup('env', 'DOCKERIZED') | bool)
