---

- name: "install LazyVim and plugins"
  ansible.builtin.command:
    cmd: mise exec -- nvim --headless "+Lazy! install" +qa
  register: neovim_plugins
  changed_when: "'Installed' in neovim_plugins.stdout"
