---

- name: "bootstrap LazyVim"
  ansible.builtin.command:
    argv:
      - mise
      - exec
      - --
      - nvim
      - --headless
      - +qa
    creates: "{{ ansible_facts['user_dir'] }}/.local/share/nvim/lazy/LazyVim"
