---

- name: "brew | list taps"
  ansible.builtin.command: brew tap
  register: brew_taps
  changed_when: false
  when: ansible_facts["system"] == "Linux"

- name: "brew | remove legacy core tap"
  ansible.builtin.command: brew untap --force homebrew/core
  when:
    - ansible_facts["system"] == "Linux"
    - "'homebrew/core' in (brew_taps.stdout_lines | default([]))"

- name: "brew | update"
  community.general.homebrew:
    update_homebrew: true
  when: not (lookup('env', 'DOCKERIZED') | bool)

- name: "brew | install taps"
  community.general.homebrew_tap:
    name: "{{ brew.taps }}"
    state: present
    trust: true

- name: "brew | install casks"
  community.general.homebrew_cask:
    name: "{{ brew.casks }}"
    state: present
    greedy: true
    accept_external_apps: true
  when:
    - ansible_facts["system"] == "Darwin"

- name: "brew | install packages"
  community.general.homebrew:
    name: "{{ pkgs }}"
