---

- name: "brew | update"
  community.general.homebrew:
    update_homebrew: true
  when: not dockerized

- name: "brew | install taps"
  community.general.homebrew_tap:
    name: "{{ brew.taps }}"
    state: present
    trust: true

- name: "brew | install casks"
  community.general.homebrew_cask:
    name: "{{ brew.casks }}"
    state: latest
    greedy: true
    accept_external_apps: true
  when:
    - ansible_facts["system"] == "Darwin"

- name: "brew | install packages"
  community.general.homebrew:
    name: "{{ pkgs }}"
    state: latest
