---

- name: "brew | list packages"
  ansible.builtin.debug:
    msg: "{{ pkgs }}"
  when: pkgs is defined

- name: "brew | update"
  community.general.homebrew:
    update_homebrew: true

- name: "brew | install taps"
  community.general.homebrew_tap:
    name: "{{ brew.taps }}"
    state: present
  when: brew.taps is defined

- name: "brew | install casks"
  community.general.homebrew_cask:
    name: "{{ brew.casks }}"
    state: present
    install_options: no-quarantine
    accept_external_apps: true
  when:
    - brew.casks is defined
    - ansible_system == "Darwin"

- name: "brew | install packages"
  community.general.homebrew:
    name: "{{ pkgs }}"
  when: pkgs is defined

- name: "brew | install packages from source"
  community.general.homebrew:
    name: "{{ brew.packages_from_source }}"
    install_options: build-from-source
  when: brew.packages_from_source is defined
