---

- block:
    - name: "packages | list homebrew tools"
      ansible.builtin.debug:
        msg: "{{ brew.packages }}"

    - name: "packages | update homebrew"
      changed_when: false
      community.general.homebrew:
        update_homebrew: true

    - name: "packages | install homebrew taps"
      community.general.homebrew_tap:
        name: "{{ brew.taps }}"
        state: present
      when: brew.taps

    - name: "packages | install homebrew casks"
      community.general.homebrew_cask:
        name: "{{ brew.casks }}"
        state: present
      when: brew.casks

    - name: "packages | install homebrew tools"
      community.general.homebrew:
        name: "{{ brew.packages }}"
      when: brew.packages

    - name: "packages | install homebrew tools from source"
      community.general.homebrew:
        name: "{{ brew.packages_from_source }}"
        install_options: build-from-source
      when: brew.packages_from_source

  tags: homebrew
