---

- name: "common | merge homebrew packages"
  ansible.builtin.set_fact:
    brew_pkgs_merged: "{{ brew.packages.common + brew.packages[ansible_facts['system'] | lower] }}"

- name: "common | install homebrew packages"
  ansible.builtin.import_tasks: brew.yaml
  vars:
    pkgs: "{{ brew_pkgs_merged }}"
  tags: homebrew
