---

- name: "apt | update"
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: "packages | install"
  become: true
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: "apt | clean"
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  when: ansible_os_family == "Debian"
