---

keyboard_modifier_mapping:
  - HIDKeyboardModifierMappingSrc: "{{ keyboard_key_codes.caps_lock }}"
    HIDKeyboardModifierMappingDst: "{{ keyboard_key_codes.escape }}"

keyboard_modifier_mapping_plist: >-
  <dict>
  <key>HIDKeyboardModifierMappingSrc</key>
  <integer>{{ keyboard_key_codes.caps_lock }}</integer>
  <key>HIDKeyboardModifierMappingDst</key>
  <integer>{{ keyboard_key_codes.escape }}</integer>
  </dict>
