---

- name: "apply keyboard modifier mapping"
  ansible.builtin.command:
    argv:
      - /usr/bin/hidutil
      - property
      - --set
      - "{{ {'UserKeyMapping': keyboard_modifier_mapping} | to_json }}"

- name: "restart preference services"
  ansible.builtin.command: /usr/bin/killall cfprefsd
  failed_when: false

- name: "restart dock"
  ansible.builtin.command: /usr/bin/killall Dock
  failed_when: false
