---

- name: "download"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh
    dest: /tmp/install-lunarvim.sh
    mode: '0755'
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5

- name: "create config dir"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/lvim"
    state: directory
    mode: '0755'

- name: "install"
  ansible.builtin.command: /tmp/install-lunarvim.sh --no-install-dependencies --yes
  args:
    creates: "{{ ansible_user_dir }}/.local/share/lunarvim"

- name: "update lunarvim dotfiles"
  ansible.builtin.command: chezmoi update --force --apply
  register: chezmoi_update
  changed_when: '"Updating" in chezmoi_update.stderr'
