---

- name: "install tools"
  ansible.builtin.command: mise install
  environment:
    GITHUB_TOKEN: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
  register: mise_install
  changed_when: "'all tools are installed' not in (mise_install.stdout + mise_install.stderr)"
