---

- name: "rectangle | set spectacle-compatible shortcuts"
  community.general.osx_defaults:
    domain: com.knollsoft.Rectangle
    key: alternateDefaultShortcuts
    type: int
    value: 0
    state: present

- name: "rectangle | launch on login"
  community.general.osx_defaults:
    domain: com.knollsoft.Rectangle
    key: launchOnLogin
    type: int
    value: 1
    state: present

