---

- name: "read current host preferences"
  ansible.builtin.command:
    argv:
      - /usr/bin/defaults
      - -currentHost
      - export
      - NSGlobalDomain
      - "-"
  register: current_host_preferences
  changed_when: false
  check_mode: false

- name: "read capslock modifier mapping"
  ansible.builtin.command:
    argv:
      - /usr/bin/plutil
      - -extract
      - com\.apple\.keyboard\.modifiermapping\.0-0-0
      - json
      - -o
      - "-"
      - --
      - "-"
    stdin: "{{ current_host_preferences.stdout }}"
  register: current_keyboard_modifier_mapping
  changed_when: false
  failed_when: current_keyboard_modifier_mapping.rc not in [0, 1]
  check_mode: false

- name: "remap capslock to escape"
  ansible.builtin.command:
    argv:
      - /usr/bin/defaults
      - -currentHost
      - write
      - NSGlobalDomain
      - com.apple.keyboard.modifiermapping.0-0-0
      - -array
      - "{{ keyboard_modifier_mapping_plist }}"
  when: >-
    current_keyboard_modifier_mapping.stdout | default('[]', true) | from_json
    != keyboard_modifier_mapping
  notify: apply keyboard modifier mapping

- name: "read alt-tab preferences"
  ansible.builtin.command:
    argv:
      - /usr/bin/defaults
      - export
      - com.lwouis.alt-tab-macos
      - "-"
  register: alt_tab_preferences
  changed_when: false
  failed_when: alt_tab_preferences.rc not in [0, 1]
  check_mode: false

- name: "read alt-tab shortcut"
  ansible.builtin.command:
    argv:
      - /usr/bin/plutil
      - -extract
      - holdShortcut
      - raw
      - -o
      - "-"
      - --
      - "-"
    stdin: "{{ alt_tab_preferences.stdout }}"
  register: alt_tab_shortcut
  changed_when: false
  failed_when: alt_tab_shortcut.rc not in [0, 1]
  check_mode: false

- name: "alt-tab | set shortcut"
  ansible.builtin.command:
    argv:
      - /usr/bin/defaults
      - write
      - com.lwouis.alt-tab-macos
      - holdShortcut
      - -string
      - "⌘"
  when: alt_tab_shortcut.stdout != '⌘'

- name: "read symbolic hotkeys preferences"
  ansible.builtin.command:
    argv:
      - /usr/bin/defaults
      - export
      - com.apple.symbolichotkeys
      - "-"
  register: symbolic_hotkeys_preferences
  changed_when: false
  failed_when: symbolic_hotkeys_preferences.rc not in [0, 1]
  check_mode: false

- name: "read symbolic hotkeys"
  ansible.builtin.command:
    argv:
      - /usr/bin/plutil
      - -extract
      - AppleSymbolicHotKeys
      - json
      - -o
      - "-"
      - --
      - "-"
    stdin: "{{ symbolic_hotkeys_preferences.stdout }}"
  register: current_symbolic_hotkeys
  changed_when: false
  failed_when: current_symbolic_hotkeys.rc not in [0, 1]
  check_mode: false

- name: "remap system shortcuts"
  ansible.builtin.command:
    argv:
      - /usr/bin/defaults
      - write
      - com.apple.symbolichotkeys
      - AppleSymbolicHotKeys
      - -dict-add
      - "{{ item.key }}"
      - "{{ symbolic_hotkey_plist }}"
  loop: "{{ darwin_hotkeys | dict2items }}"
  when: >-
    (current_symbolic_hotkeys.stdout | default('{}', true) | from_json)
    [item.key | string] | default({})
    != {
      'enabled': item.value.enabled,
      'value': {
        'parameters': item.value.parameters,
        'type': 'standard'
      }
    }
  notify: restart preference services
