---

- name: "remap capslock to escape"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    host: currentHost
    key: com.apple.keyboard.modifiermapping.0-0-0
    type: array
    value: "{{ keyboard_modifier_mapping }}"
  notify: apply keyboard modifier mapping

- name: "remap system shortcuts"
  community.general.osx_defaults:
    domain: com.apple.symbolichotkeys
    key: AppleSymbolicHotKeys
    type: dict
    dict_mode: add
    value: >-
      {{
        {
          item.key | string: {
            'enabled': item.value.enabled,
            'value': {
              'parameters': item.value.parameters,
              'type': 'standard'
            }
          }
        }
      }}
  loop: "{{ darwin_hotkeys | dict2items }}"
  notify: restart preference services
