---

- name: "remap capslock to escape"
  macos_defaults_plist:
    domain: NSGlobalDomain
    current_host: true
    key: com.apple.keyboard.modifiermapping.0-0-0
    value_type: array
    value: "{{ keyboard_modifier_mapping }}"
  notify: apply keyboard modifier mapping

- name: "remap system shortcuts"
  macos_defaults_plist:
    domain: com.apple.symbolichotkeys
    key: AppleSymbolicHotKeys
    value_type: dict
    dict_mode: add
    value: "{{ darwin_hotkeys }}"
  notify: restart preference services
