#!/usr/bin/env bash
# Disposable sandbox for the README demo recording.
#
# Everything the recording touches is created here, so the render can never
# reach the live tmux server, the real kubeconfig (which carries corporate
# contexts), or any real git repository. Nothing outside $SANDBOX is written,
# and `down` removes only what `up` created.
#
# Usage:
#   ./sandbox.sh up      provision, idempotent
#   ./sandbox.sh down    destroy everything this script created
#   ./sandbox.sh reset   return the mutable state to its post-up condition
#   ./sandbox.sh env     print sandbox paths as shell assignments
#   ./sandbox.sh check   assert the sandbox is isolated (both called by
#                        render.sh before every recording)

set -euo pipefail

readonly CLUSTER=dotfiles-demo
readonly CONTEXT="kind-${CLUSTER}"

DEMO_DIR=$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
readonly DEMO_DIR
readonly REPO_ROOT="${DEMO_DIR%/demo}"
readonly SRC="${REPO_ROOT}/config/private_dot_config"

SANDBOX="${DEMO_SANDBOX:-${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles-demo}"
readonly SANDBOX
readonly TMUX_SOCKET="${SANDBOX}/tmux.sock"
readonly TMUX_CONF="${SANDBOX}/tmux.conf"
readonly KUBECONFIG_FILE="${SANDBOX}/kubeconfig"
readonly K9S_DIR="${SANDBOX}/k9s"
readonly WORK_REPO="${SANDBOX}/repo"

log() { printf '\033[38;2;130;170;255m==>\033[0m %s\n' "$*" >&2; }
die() {
  printf '\033[38;2;255;117;127mERROR\033[0m %s\n' "$*" >&2
  exit 1
}

# kubectl and k9s are mise-managed, and mise's per-directory environment is
# injected only by an interactive shell hook. Route through `mise exec` so this
# script works when run non-interactively (CI, agent tool calls).
run() {
  if command -v mise > /dev/null 2>&1; then
    mise exec -- "$@"
  else
    "$@"
  fi
}

# --- tmux ---------------------------------------------------------------------

# The recording needs the real tmux config to be worth showing, but two parts of
# it reach outside the sandbox and are dropped here:
#
#   workmux sidebar  a 30-column pane listing live agent worktrees, which is
#                    both a leak and a third of the frame
#   tpm              loads plugins from ~/.config/tmux/plugins, so the result
#                    would depend on the recording machine's plugin state
#
# Both are matched by keyword, including their `if-shell` continuation lines, so
# no half-statement survives. `check` re-asserts that afterwards.
generate_tmux_conf() {
  local fish
  fish=$(command -v fish) || die 'fish not found'

  {
    # shellcheck disable=SC2016 # backticks are markdown, not a subshell
    printf '%s\n%s\n\n' \
      '# Generated by demo/sandbox.sh from the tmux.conf in this repository.' \
      '# Do not edit: regenerated on every `sandbox.sh up`.'
    grep -v -E 'workmux|@plugin|tpm' "${SRC}/private_tmux/tmux.conf"
    printf '\n# --- sandbox overrides ---\n'
    # $SHELL leaks in from whichever shell starts the render, so pin the pane
    # shell instead of inheriting it.
    printf 'set -g default-shell %s\n' "$fish"
    # The stock config prompts for a window name after every unnamed window
    # (after-new-window hook). The tape creates windows with explicit names, but
    # drop the hook so a stray prompt can never hijack the recording.
    printf 'set-hook -gu after-new-window\n'
    # Recording is fixed-size; the status bar is the only thing that needs to be
    # legible at GIF scale.
    printf 'set -g status-interval 1\n'
  } > "$TMUX_CONF"

  # Sourcing happens on server start, so a real session is the only honest
  # test that the filtered config still loads.
  local probe="${TMUX_SOCKET}.probe"
  rm -f "$probe"
  if ! run tmux -S "$probe" -f "$TMUX_CONF" new-session -d -s probe 2>&1; then
    die "generated tmux.conf is not loadable: ${TMUX_CONF}"
  fi
  run tmux -S "$probe" kill-server 2> /dev/null || true
  rm -f "$probe"
}

# --- k9s ----------------------------------------------------------------------

# K9S_CONFIG_DIR redirects both config and state. Copying the repo's k9s config
# gives the real tokyonight_moon skin without k9s writing context history back
# into ~/.config/k9s.
stage_k9s_config() {
  rm -rf "$K9S_DIR"
  mkdir -p "$K9S_DIR"
  cp -R "${SRC}/k9s/." "$K9S_DIR/"
}

# --- cluster ------------------------------------------------------------------

provision_cluster() {
  # Every kind invocation is pinned to the sandbox kubeconfig. Without the flag
  # kind falls back to ~/.kube/config and would edit the real one, on delete as
  # much as on create.
  : >> "$KUBECONFIG_FILE"

  if run kind get clusters 2> /dev/null | grep -qx "$CLUSTER"; then
    log "kind cluster ${CLUSTER} already exists"
  else
    log "creating kind cluster ${CLUSTER}"
    run kind create cluster --name "$CLUSTER" \
      --kubeconfig "$KUBECONFIG_FILE" --wait 120s
  fi

  # `create --kubeconfig` writes only at creation time, so export every run to
  # keep the sandbox kubeconfig valid for a pre-existing cluster too.
  run kind export kubeconfig --name "$CLUSTER" --kubeconfig "$KUBECONFIG_FILE"

  seed_workloads
}

# Gives k9s something worth looking at: three namespaces, a few replica sets and
# a service. Images are alpine-based to keep the pull short.
seed_workloads() {
  log 'applying demo workloads'
  run kubectl --kubeconfig "$KUBECONFIG_FILE" apply -f - << 'MANIFEST' > /dev/null
apiVersion: v1
kind: Namespace
metadata: { name: storefront }
---
apiVersion: v1
kind: Namespace
metadata: { name: payments }
---
apiVersion: v1
kind: Namespace
metadata: { name: observability }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: web, namespace: storefront }
spec:
  replicas: 3
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
        - name: nginx
          image: nginx:1.29-alpine
          ports: [{ containerPort: 80 }]
          resources:
            requests: { cpu: 10m, memory: 16Mi }
---
apiVersion: v1
kind: Service
metadata: { name: web, namespace: storefront }
spec:
  selector: { app: web }
  ports: [{ port: 80, targetPort: 80 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: checkout-api, namespace: payments }
spec:
  replicas: 2
  selector: { matchLabels: { app: checkout-api } }
  template:
    metadata: { labels: { app: checkout-api } }
    spec:
      containers:
        - name: nginx
          image: nginx:1.29-alpine
          resources:
            requests: { cpu: 10m, memory: 16Mi }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: ledger, namespace: payments }
spec:
  replicas: 1
  selector: { matchLabels: { app: ledger } }
  template:
    metadata: { labels: { app: ledger } }
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          resources:
            requests: { cpu: 10m, memory: 16Mi }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: metrics-collector, namespace: observability }
spec:
  replicas: 2
  selector: { matchLabels: { app: metrics-collector } }
  template:
    metadata: { labels: { app: metrics-collector } }
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          resources:
            requests: { cpu: 10m, memory: 16Mi }
MANIFEST

  log 'waiting for rollouts'
  local ns dep
  for ns in storefront payments observability; do
    while read -r dep; do
      [[ -n "$dep" ]] || continue
      run kubectl --kubeconfig "$KUBECONFIG_FILE" -n "$ns" \
        rollout status "$dep" --timeout=180s > /dev/null
    done < <(run kubectl --kubeconfig "$KUBECONFIG_FILE" -n "$ns" \
      get deploy -o name 2> /dev/null)
  done
}

# --- demo repository ----------------------------------------------------------

# lazygit and nvim both need a repository. A synthetic one keeps real branch
# names, commit messages and remotes out of the frame, and makes the diff shown
# in lazygit identical on every render.
seed_repo() {
  log 'seeding demo git repository'
  rm -rf "$WORK_REPO"
  mkdir -p "$WORK_REPO"

  git -C "$WORK_REPO" init -q -b main

  # The user's git config sets user.useConfigOnly=true and resolves identity
  # through includeIf rules keyed on path and remote; none match a sandbox under
  # ~/.cache, so without a local identity every commit here would fail. Signing
  # is disabled for the same reason it is never disabled in the real repo: it is
  # the *only* thing that would make an unattended render sit waiting for a
  # 1Password Touch ID prompt. This repository is a throwaway fixture with no
  # remote; nothing it contains is ever published.
  git -C "$WORK_REPO" config user.name 'Ada Lovelace'
  git -C "$WORK_REPO" config user.email 'ada@example.com'
  git -C "$WORK_REPO" config commit.gpgsign false
  git -C "$WORK_REPO" config tag.gpgsign false
  # Avoid leaving a per-repo watcher daemon behind for a directory we delete.
  git -C "$WORK_REPO" config core.fsmonitor false

  mkdir -p "$WORK_REPO"/{tmux,lazygit,k9s/skins,opencode/themes,nvim/lua/plugins}

  cat > "$WORK_REPO/README.md" << 'EOF'
# terminal

TokyoNight moon, end to end: alacritty, tmux, neovim, lazygit, k9s.

| Layer    | Config                          |
| -------- | ------------------------------- |
| terminal | alacritty + FiraCode Nerd Font  |
| mux      | tmux, prefix `C-a`              |
| editor   | neovim / LazyVim                |
| git      | lazygit + delta                 |
| k8s      | k9s                             |
EOF

  cp "${SRC}/private_tmux/tmux.conf" "$WORK_REPO/tmux/tmux.conf"
  cp "${SRC}/lazygit/config.yml" "$WORK_REPO/lazygit/config.yml"
  cp "${SRC}/k9s/skins/tokyonight_moon.yaml" "$WORK_REPO/k9s/skins/tokyonight_moon.yaml"
  cp "${SRC}/private_opencode/themes/tokyonight-transparent.json" \
    "$WORK_REPO/opencode/themes/tokyonight-transparent.json"

  cat > "$WORK_REPO/nvim/lua/plugins/tokyonight.lua" << 'EOF'
-- Single source of truth for the palette every other tool copies.
return {
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      style = "moon",
      transparent = true,
      styles = {
        sidebars = "transparent",
        floats = "transparent",
      },
      on_colors = function(colors)
        colors.border = "#3b4261"
      end,
    },
  },
}
EOF

  git -C "$WORK_REPO" add -A
  git -C "$WORK_REPO" commit -q -m 'Add terminal stack overview'

  cat >> "$WORK_REPO/tmux/tmux.conf" << 'EOF'

# Dim inactive panes so the focused one reads first.
setw -g window-style 'bg=#1e2030'
setw -g window-active-style 'bg=#222436'
EOF
  git -C "$WORK_REPO" add -A
  git -C "$WORK_REPO" commit -q -m 'tmux: dim inactive panes to the status-bar shade'

  cat >> "$WORK_REPO/README.md" << 'EOF'

Every tool reads the same six hex values, so a palette change is one commit:

- `#222436` background
- `#1e2030` dimmed background
- `#c8d3f5` foreground
- `#82aaff` accent
- `#ffc777` warning
- `#ff757f` danger
EOF
  git -C "$WORK_REPO" add -A
  git -C "$WORK_REPO" commit -q -m 'README: document the shared palette'

  # Comments only: this copy is a fixture shown in the editor, and a new
  # structural key would not round-trip through k9s' skin schema.
  cat >> "$WORK_REPO/k9s/skins/tokyonight_moon.yaml" << 'EOF'

# Backgrounds stay `default` on purpose: the terminal and tmux own the
# background, so tmux's inactive-pane dimming still shows through k9s.
EOF
  git -C "$WORK_REPO" add -A
  git -C "$WORK_REPO" commit -q -m 'k9s: explain the default background choice'

  # Branch name matches the lazygit commitPrefix pattern, so the commit message
  # panel prefills "[DOT-42] ".
  git -C "$WORK_REPO" checkout -q -b feature/DOT-42-tokyonight-palette

  # One staged and one unstaged change, so lazygit opens with both sections
  # populated and a delta diff already on screen.
  # Staged: an in-place edit rather than an append, so the file stays valid
  # Lua. Nothing may follow a top-level `return`, which is what an append
  # here would produce.
  local lua='nvim/lua/plugins/tokyonight.lua'
  # Indentation is literal rather than captured: the fixture is written a few
  # lines above, so the depth is known and no capture group is needed (which
  # also keeps the substitution free of anything shell-expandable).
  local subst='s/^        colors\.border = "#3b4261"$/'
  subst+='        colors.border = "#589ed7"\n'
  subst+='        colors.bg_float = "#1e2030"\n'
  subst+='        colors.bg_sidebar = "#1e2030"/'
  perl -pi -e "$subst" "${WORK_REPO}/${lua}"
  git -C "$WORK_REPO" add "$lua"

  # Unstaged: tmux.conf is line-based, so an append is always valid.
  cat >> "$WORK_REPO/tmux/tmux.conf" << 'EOF'

# Surface copy mode in the status bar; the border cue alone is too subtle.
set -g status-left '#{?pane_in_mode,#[bg=#ffc777] COPY ,}'
EOF
}

# --- commands -----------------------------------------------------------------

cmd_up() {
  command -v git > /dev/null || die 'git not found'
  run kind version > /dev/null 2>&1 || die 'kind not found'
  run docker info > /dev/null 2>&1 \
    || die 'docker is not responding; start Docker/Rancher Desktop first'

  mkdir -p "$SANDBOX"
  generate_tmux_conf
  stage_k9s_config
  seed_repo
  provision_cluster
  cmd_check
  log "sandbox ready at ${SANDBOX}"
}

cmd_down() {
  if [[ -S "$TMUX_SOCKET" ]]; then
    log 'killing sandbox tmux server'
    run tmux -S "$TMUX_SOCKET" kill-server 2> /dev/null || true
  fi
  if run kind get clusters 2> /dev/null | grep -qx "$CLUSTER"; then
    log "deleting kind cluster ${CLUSTER}"
    : >> "$KUBECONFIG_FILE"
    run kind delete cluster --name "$CLUSTER" \
      --kubeconfig "$KUBECONFIG_FILE" > /dev/null
  fi
  if [[ -d "$SANDBOX" ]]; then
    log "removing ${SANDBOX}"
    rm -rf "$SANDBOX"
  fi
}

# Fails the render rather than recording a frame that points at live state.
cmd_check() {
  [[ -f "$KUBECONFIG_FILE" ]] || die "missing ${KUBECONFIG_FILE}"
  [[ -f "$TMUX_CONF" ]] || die "missing ${TMUX_CONF}"
  [[ -d "$WORK_REPO/.git" ]] || die "missing ${WORK_REPO}/.git"
  [[ -f "${K9S_DIR}/skins/tokyonight_moon.yaml" ]] || die "missing skin in ${K9S_DIR}"

  local contexts
  contexts=$(run kubectl --kubeconfig "$KUBECONFIG_FILE" config get-contexts -o name)
  [[ "$contexts" == "$CONTEXT" ]] \
    || die "sandbox kubeconfig is not isolated, contexts: ${contexts//$'\n'/ }"

  # `cmd && die` would trip `set -e` on the common no-match path, so these stay
  # explicit conditionals.
  if grep -q 'workmux' "$TMUX_CONF"; then
    die 'generated tmux.conf still references workmux'
  fi
  if grep -qE '@plugin|tpm' "$TMUX_CONF"; then
    die 'generated tmux.conf still loads tpm plugins'
  fi
  if [[ -n "$(git -C "$WORK_REPO" remote)" ]]; then
    die 'demo repo must have no remote'
  fi

  log 'sandbox isolation verified'
}

# Restores the mutable parts of the sandbox to their post-`up` state, so two
# renders record the same thing. k9s is the reason this exists: it persists the
# active view and namespace into K9S_CONFIG_DIR, so a second render would open
# on whichever screen the previous one happened to end on. The repository is
# reseeded for the same reason, cheaply, in case a stray keystroke reached a
# buffer or the index.
cmd_reset() {
  stage_k9s_config
  seed_repo
  log 'sandbox state reset'
}

cmd_env() {
  printf 'DEMO_SANDBOX=%s\n' "$SANDBOX"
  printf 'DEMO_TMUX_SOCKET=%s\n' "$TMUX_SOCKET"
  printf 'DEMO_TMUX_CONF=%s\n' "$TMUX_CONF"
  printf 'DEMO_REPO=%s\n' "$WORK_REPO"
  printf 'KUBECONFIG=%s\n' "$KUBECONFIG_FILE"
  printf 'K9S_CONFIG_DIR=%s\n' "$K9S_DIR"
}

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down ;;
  check) cmd_check ;;
  env) cmd_env ;;
  reset) cmd_reset ;;
  *) die "usage: ${0##*/} {up|down|reset|check|env}" ;;
esac
