[settings]
experimental = true
legacy_version_file = false

[tools]
"aqua:helm" = "3.16.3"
"aqua:kubectl" = "1.32.0"
"aqua:pre-commit" = "4.0.1"
"aqua:terraform" = "1.14.8"
"aqua:terraform-ls" = "0.36.2"
"aqua:terramate" = "0.11.7"
go = "1.26.2"
maven = "3.9.9"
node = "22.13.0"
python = "3.14.3"
ruby = "3.4.1"
vault = "1.21.4"
yarn = "4.13.0"
