[settings]
experimental = true
legacy_version_file = false

[tools]
"aqua:helm" = "3.16.3"
"aqua:kubectl" = "1.32.0"
"aqua:pre-commit" = "4.0.1"
"aqua:terraform" = "1.10.2"
"aqua:terraform-ls" = "0.36.2"
"aqua:terramate" = "0.11.4"
go = "1.23.4"
node = "22.12.0"
python = "3.13.1"
ruby = "3.3.6"
