[settings]
experimental = true
legacy_version_file = false

[tools]
"aqua:helm" = "4.2.4"
"aqua:kubectl" = "1.37.0"
"aqua:aws/aws-cli" = "2"
"aqua:derailed/k9s" = "0.50"
"aqua:hadolint/hadolint" = "2"
"aqua:kubernetes-sigs/kustomize" = "5"
"aqua:LuaLS/lua-language-server" = "3"
"aqua:neovim/neovim" = "0.12"
"aqua:terraform" = "1.15.8"
"aqua:terraform-ls" = "0.39.0"
"aqua:terraform-docs/terraform-docs" = "0"
"aqua:terraform-linters/tflint" = "0"
"aqua:terramate" = "0.17.2"
"aqua:tree-sitter/tree-sitter" = "0"
"aqua:aquasecurity/tfsec" = "1"
"go:golang.org/x/tools/gopls" = "latest"
"pipx:ansible-lint" = "26"
"pipx:azure-cli" = "2"
"pipx:yamllint" = "1"
bun = "latest"
go = "1.26.7"
maven = "3.9.16"
node = "24.18.1"
prek = "latest"
python = "3.14.7"
ruby = "4.0.6"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
vault = "1.21.4"
