#!/usr/bin/env fish

#######################################################################
#                               General                               #
#######################################################################

# source fzf binds
fzf_key_bindings

# enable vi mode
set -U fish_key_bindings fish_vi_key_bindings
# and now restore ctrl+f for autocomplete and fzf binds
# https://github.com/fish-shell/fish-shell/issues/3541
function fish_user_key_bindings
   for mode in insert default visual
      bind -M $mode \cf forward-char
      bind -M $mode \ct fzf-file-widget
      bind -M $mode \cr fzf-history-widget
      bind -M $mode \ec fzf-cd-widget
   end
end

#######################################################################
#                               Aliases                               #
#######################################################################

if which subl &>/dev/null
   alias s subl
end

alias g git
alias r 'source ~/.config/fish/config.fish'
alias ssh 'assh wrapper ssh --'
alias p 'cd ~/projects'
alias w 'cd ~/work'
alias d 'cd ~/dotfiles'
alias tree 'tree -a -I ".git|*.pyc|*pycache*"'

#######################################################################
#                          Windows-specific                           #
#######################################################################

if grep -qE "(Microsoft|WSL)" /proc/version &>/dev/null
   if [ "(umask)" = "0000" ]
      umask 0022
   end

   function proxy
      if [ -f ~/.proxy ]
         rm ~/.proxy
         rm ~/.gitconfig.proxy
      else
         ln -s ~/dotfiles/.proxy ~/.proxy
         ln -s ~/dotfiles/.gitconfig.proxy ~/.gitconfig.proxy
      end
   end

   function dnsfix
      set -lx search (grep -F "search" /etc/resolv.conf)
      set -lx ipv4dnsraw (/mnt/c/Windows/system32/netsh.exe \
         interface ip show dns | tr -d '\r');
      set -lx ipv6dnsraw (/mnt/c/Windows/system32/netsh.exe \
         interface ipv6 show dns | tr -d '\r');
      set -lx nameservers (printf '%s\n%s\n' \
         $ipv4dnsraw $ipv6dnsraw | grep -iF "DNS Servers" | grep -v "None" \
         | cut -c 43- |  uniq | sed 's/^/nameserver /')
      printf '%s on %s\n%s\n%s\n' '# generated by dnsfix' (date) \
         $nameservers $search | sudo tee /etc/resolv.conf >/dev/null;
   end

   # https://github.com/yuk7/ArchWSL/issues/109
   alias rg "rg -j1 --hidden -i"

   # Source corporate proxy if exists
   if [ -f ~/.proxy ]; . \
      ~/.proxy; end

      # Fix DNS when connecting through VPN
      dnsfix
   end

   # The next line updates PATH for the Google Cloud SDK.
   if [ -f '/Users/esolidarity/google-cloud-sdk/path.fish.inc' ]; . \
      '/Users/esolidarity/google-cloud-sdk/path.fish.inc'; end

      #######################################################################
      #                               Exports                               #
      #######################################################################

      set -gx FZF_DEFAULT_COMMAND "rg --files --hidden --follow --glob '!.git'"
      set -gx FZF_DEFAULT_OPTS "--color=dark"

      set -gx GOPATH ~/go
      set -gx GOBIN "$GOPATH/bin"
      set -gx PATH "$GOBIN" $PATH

      #######################################################################
      #                               Functions                             #
      #######################################################################

      function fif --description="Using ripgrep combined with preview"
         if test (count $argv) -lt 1; or test $argv[1] = "--help"
            printf "Need a string to search for."
         else if test (count $argv) -eq 1
            rg --files-with-matches --no-messages "$argv[1]" | fzf --preview \
               "rg  --ignore-case --pretty --context 10 '$argv[1]'"
         end
      end
