---

- name: "install anyenv"
  community.general.homebrew:
    name: anyenv
  tags: homebrew

- name: "init anyenv"
  ansible.builtin.command: anyenv install --force-init
  args:
    creates: "{{ ansible_user_dir }}/.config/anyenv/anyenv-install"

- name: "install anyenv-update"
  ansible.builtin.git:
    repo: https://github.com/znz/anyenv-update.git
    dest: "{{ ansible_user_dir }}/.anyenv/plugins/anyenv-update"
    version: master

- name: "echo PATH"
  command: echo "$PATH"
  register: default_path

- name: "echo anyenv PATH"
  command: echo "$HOME/.anyenv"
  register: anyenv_home

- name: "install envs"
  environment:
    PATH: "{{ anyenv_home.stdout }}/bin:{{ default_path.stdout }}"
  shell: |
    anyenv install {{ item.env }}
  args:
    executable: /bin/bash
    creates: "{{ ansible_user_dir }}/.anyenv/envs/{{ item.env }}"
  with_items:
    - env: nodenv
    - env: goenv
    - env: pyenv

- name: "install language"
  environment:
    PATH: "{{ anyenv_home.stdout }}/bin:{{ default_path.stdout }}"
  shell: |
    eval "$(anyenv init - bash)"
    {{ item.env }} install {{ item.version  }}
    {{ item.env }} rehash
    {{ item.env }} global {{ item.version }}
  args:
    executable: /bin/bash
    creates: "{{ ansible_user_dir }}/.anyenv/envs/{{ item.env }}/versions/{{ item.version }}"
  with_items:
    - env: nodenv
      version: '{{ nodejs.versions[0] }}'
    - env: goenv
      version: '{{ golang.versions[0] }}'
