---

- name: "install anyenv"
  community.general.homebrew:
    name: anyenv
  tags: homebrew

- name: "init anyenv"
  ansible.builtin.command: anyenv install --force-init
  args:
    creates: "{{ ansible_user_dir }}/.config/anyenv/anyenv-install"

- name: "install anyenv-update"
  ansible.builtin.git:
    repo: https://github.com/znz/anyenv-update.git
    dest: "{{ ansible_user_dir }}/.anyenv/plugins/anyenv-update"
    version: master
