---

apt_packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim

homebrew_taps:
  # - aws/tap
  # - carlocab/personal
  # - go-task/tap
  # - hashicorp/tap
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core
  # - trussworks/tap


homebrew_casks:
  - font-fira-code-nerd-font

homebrew_packages:
  - asdf
  - bat
  - direnv
  - exa
  - fd
  - gh
  - ghq
  - ripgrep

homebrew_packages_from_source:
  - duf
