---
name: idempotence

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Clean up installed software
        run: |
          while IFS= read -r formula; do
            brew uninstall --ignore-dependencies --force "$formula"
          done < <(brew list --formula)
          while IFS= read -r cask; do
            brew uninstall --cask --force "$cask"
          done < <(brew list --cask)
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install
        run: ./scripts/setup.sh --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run playbook again
        run: |
          ./scripts/common/ansible.sh --run | tee /tmp/ansible-idempotence.log
          grep -Eq 'changed=0 +unreachable=0 +failed=0' /tmp/ansible-idempotence.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
