---
name: macos

on:
  push:
    branches:
      - 'master'
    paths:
      - 'config/**'
      - 'scripts/**'
      - '.github/workflows/macos.yaml'
      - '!**.md'
      - '!.github/mkdocs.yaml'
      - '!docs/**'

jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]

    steps:
      - name: Clean up installed software
        if: startsWith(matrix.os, 'macos')
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          brew uninstall --cask --force firefox google-chrome
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

      # - name: Download and install available system updates
      #   if: startsWith(matrix.os, 'macos')
      #   run: |
      #     sudo softwareupdate -i -a

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install using setup.sh
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            ./scripts/setup.sh --all
          fi
