---
name: macos

on:
  push:
    paths:
      - "config/**"
      - "scripts/**"
      - ".ansible-lint"
      - ".pre-commit-config.yaml"
      - ".yamllint.yaml"
      - ".github/workflows/macos.yaml"
      - "!**.md"
      - "!.github/mkdocs.yaml"
      - "!docs/**"

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Clean up installed software
        run: |
          while IFS= read -r formula; do
            brew uninstall --ignore-dependencies --force "$formula"
          done < <(brew list --formula)
          while IFS= read -r cask; do
            brew uninstall --cask --force "$cask"
          done < <(brew list --cask)
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

      # - name: Download and install available system updates
      #   if: startsWith(matrix.os, 'macos')
      #   run: |
      #     sudo softwareupdate -i -a

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install using setup.sh
        run: ./scripts/setup.sh --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate
        run: mise exec -- prek run --all-files
