---

ansible_python_interpreter: "{{ ansible_playbook_python }}"
dockerized: "{{ lookup('ansible.builtin.env', 'DOCKERIZED') == 'true' }}"
persistent_checkout: >-
  {{ lookup('ansible.builtin.env', 'DOTFILES_PERSISTENT_CHECKOUT') }}
persistent_repository_url: >-
  {{ lookup('ansible.builtin.env', 'DOTFILES_PERSISTENT_REPOSITORY_URL') }}
persistent_repository_ref: >-
  {{ lookup('ansible.builtin.env', 'DOTFILES_PERSISTENT_REF') }}
persistent_repository_refspec: >-
  {{ lookup('ansible.builtin.env', 'DOTFILES_PERSISTENT_REFSPEC') }}
persistent_repository_expected_commit: >-
  {{ lookup('ansible.builtin.env', 'DOTFILES_PERSISTENT_EXPECTED_COMMIT') }}
workstation_path: >-
  {{
    '/opt/homebrew/bin:/opt/homebrew/sbin:'
    + '/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:'
    + lookup('ansible.builtin.env', 'PATH')
  }}
